[project]
name = "embind-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clang>=20.1.5",
    "mako>=1.3.10",
    "pyyaml>=6.0.2",
]
